-- CREATING THE EMPTY TYPE FOR THE dept_t
CREATE TYPE dept_t
/

-- CREATING THE TYP EOF THE OBEJCT FOR THE emp_t
CREATE TYPE emp_t AS OBJECT (
    EMPNO CHAR(6),
    FIRSTNAME VARCHAR(12),
    LASTNAME VARCHAR(15),
    WORKDEPT REF dept_t,
    SEX CHAR(1),
    BIRTHDAY DATE,
    SALARY NUMBER(8,2)
)
/
-- CREATING THE TYPE OF THE OBJECT FOR THE dept_t
CREATE TYPE dept_t AS OBJECT (
    DEPTNO CHAR(3),
    DEPTNAME VARCHAR(36),
    MGRNO REF emp_t,
    ADMRDEPT REF dept_t
)
/

-- CREATING THE TABLE FOR THE emp_t TYPE.
CREATE TABLE OREMP of emp_t (
    CONSTRAINT OREMP_PK PRIMARY KEY(EMPNO),
    CONSTRAINT OREMP_FIRSTNAME_NN FIRSTNAME NOT NULL , 
    CONSTRAINT OREMP_LASTNAME_NN LASTNAME NOT NULL,
    CONSTRAINT OREMP_SEC_CK CHECK (SEX='M' OR SEX='F' OR SEX='m' or SEX='f')
)
/

CREATE TABLE ORDEPT of dept_t (
    CONSTRAINT OEDEPT_PK PRIMARY KEY(DEPTNO),
    CONSTRAINT ORDEPT_DEPTNAME_NN DEPTNAME NOT NULL,
    CONSTRAINT ORDEPT_MGRNO_FK FOREIGN KEY(MGRNO) REFERENCES OREMP,
    CONSTRAINT ORDEPT_ADMRDEPT_FK FOREIGN KEY (ADMRDEPT) REFERENCES ORDEPT
)
/

-- ALTERING THE DEPT TABLE AND ADDING A FOREIGN KEY CONSTRAINT TO IT.
ALTER TABLE OREMP ADD CONSTRAINT OREMP_WORKDEPT_FK FOREIGN KEY(WORKDEPT) REFERENCES ORDEPT

-- DATA INSERT QUERIES.
INSERT INTO ORDEPT VALUES (DEPT_T('A00', 'SPIFFY SERVICE DIV', NULL, NULL))
INSERT INTO ORDEPT VALUES (DEPT_T('B01', 'Planning', NULL, (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00')))
INSERT INTO ORDEPT VALUES (DEPT_T('C01', 'Information Center', NULL, (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00')))
INSERT INTO ORDEPT VALUES (DEPT_T('D01', 'Development Center', NULL, (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'C01')))
