-- CREATING THE EMPTY TYPE FOR THE dept_t
CREATE TYPE dept_t
/

-- CREATING THE TYP EOF THE OBEJCT FOR THE emp_t
CREATE TYPE emp_t AS OBJECT (
    EMPNO CHAR(6),
    FIRSTNAME VARCHAR(12),
    LASTNAME VARCHAR(15),
    WORKDEPT REF dept_t,
    SEX CHAR(1),
    BIRTHDAY DATE,
    SALARY NUMBER(8,2)
)
/
-- CREATING THE TYPE OF THE OBJECT FOR THE dept_t
CREATE TYPE dept_t AS OBJECT (
    DEPTNO CHAR(3),
    DEPTNAME VARCHAR(36),
    MGRNO REF emp_t,
    ADMRDEPT REF dept_t
)
/

-- CREATING THE TABLE FOR THE emp_t TYPE.
CREATE TABLE OREMP of emp_t (
    CONSTRAINT OREMP_PK PRIMARY KEY(EMPNO),
    CONSTRAINT OREMP_FIRSTNAME_NN FIRSTNAME NOT NULL , 
    CONSTRAINT OREMP_LASTNAME_NN LASTNAME NOT NULL,
    CONSTRAINT OREMP_SEC_CK CHECK (SEX='M' OR SEX='F' OR SEX='m' or SEX='f')
)
/

CREATE TABLE ORDEPT of dept_t (
    CONSTRAINT OEDEPT_PK PRIMARY KEY(DEPTNO),
    CONSTRAINT ORDEPT_DEPTNAME_NN DEPTNAME NOT NULL,
    CONSTRAINT ORDEPT_MGRNO_FK FOREIGN KEY(MGRNO) REFERENCES OREMP,
    CONSTRAINT ORDEPT_ADMRDEPT_FK FOREIGN KEY (ADMRDEPT) REFERENCES ORDEPT
)
/

-- ALTERING THE DEPT TABLE AND ADDING A FOREIGN KEY CONSTRAINT TO IT.
ALTER TABLE OREMP ADD CONSTRAINT OREMP_WORKDEPT_FK FOREIGN KEY(WORKDEPT) REFERENCES ORDEPT

-- DATA INSERT QUERIES.
INSERT INTO ORDEPT VALUES (DEPT_T('A00', 'SPIFFY SERVICE DIV', NULL, NULL))
INSERT INTO ORDEPT VALUES (DEPT_T('B01', 'Planning', NULL, (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00')))
INSERT INTO ORDEPT VALUES (DEPT_T('C01', 'Information Center', NULL, (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00')))
INSERT INTO ORDEPT VALUES (DEPT_T('D01', 'Development Center', NULL, (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'C01')))

-- UPDATE QUERY TO UPDATE THE ADMIN DEPART IN THE FIRST ONE.
UPDATE ORDEPT d
SET d.ADMRDEPT = (SELECT REF(D) FROM ORDEPT d WHERE d.DEPTNO = 'A00')
WHERE d.DEPTNO = 'A00' 

-- INSERTING VALUES INTO OREMP TABLE.
INSERT INTO OREMP VALUES (EMP_T('000010', 'Christine', 'Haas', (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00'), 'F', '14-Aug-1953', 72750))
INSERT INTO OREMP VALUES (EMP_T('000020', 'Michael', 'Thompson', (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00'), 'F', '02-Feb-1968', 61250))
INSERT INTO OREMP VALUES (EMP_T('000030', 'Sally', 'Kwan', (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00'), 'F', '11-May-1971', 58250))
INSERT INTO OREMP VALUES (EMP_T('000060', 'Irving', 'Stern', (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00'), 'F', '07-Jul-1965', 55555))
INSERT INTO OREMP VALUES (EMP_T('000070', 'Eva', 'Pulaski', (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00'), 'F', '26-May-1973', 56170))
INSERT INTO OREMP VALUES (EMP_T('000050', 'John', 'Geyer', (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00'), 'F', '15-Sep-1955', 60175))
INSERT INTO OREMP VALUES (EMP_T('000090', 'Eileen', 'henderson', (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00'), 'F', '15-May-1961', 49750))
INSERT INTO OREMP VALUES (EMP_T('000100', 'Theodore', 'Spenser', (SELECT REF(d) FROM ORDEPT d WHERE d.DEPTNO = 'A00'), 'F', '18-Dec-1976', 46150))